### ISSUE TITLE
[Refactor] Environment Variables into Library Function

### ISSUE THREAD

**Issue by cchan9528** [cchan9528/ServerlessImageProcessing#3]
### Situation
Environment variables are based on a file right now. 
This is not only breaking sls-offline, but it's also not realistic since these values would come from system and not a file.

### Ask
Create a library/shared function to gather necessary environment variables

**Comment by cchan9528** [comment]
```
fetchData:
  handler: src/fetchData/handler.js
  environment: ${file(./${self:custom.stage}.env.json)}
}
```

This lets you import a bunch of key values 
https://tinyurl.com/dt5fteve
